### PR TITLE
Add pending counts to services

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Various suggestions from previous PRs and other minor cleanup.

### CODE REVIEW

**Comment by madoleary** [comment]
s.points.where(status: 'pending').count

I think it would be better to have this logic in an instance method on service, so that inside of the Service model you have a method like this:

def pending_points_count
     points.where(status: 'pending').count
end 

And then in the view, it can be called like this: s.pending_points_count. This will make the logic available to unit tests (when we get around to making tests :)). And it keeps the database query out of the view, isolating it to the model.

@services = Service.includes(points: [:case]).all needs to be added back for the time being. To get the rating for each service, we're making multiple calls to points and their case. See the "service_rating_get" method in the Service model. We've had discussions in the past about finding a more efficient way to calculate these ratings, so we're very open to suggestions, on that front. I've recently been thinking about having a rating column for services, and updating it via some type of cron task that runs once or twice a day, or more often, depending on how demanding it is for the servers.

There's no existing "rating" column for services. It only exists on case, which passes it to point. We tally the ratings of the points, then use that to calculate a type of balance, which determines the rating of the service.

**Comment by JesseWeinstein** [comment]
Sure, I can factor `s.points.where(status: 'pending').count` out into a method.

The removal of `@services = Service.includes(points: [:case]).all` is because it's already being called by the `before_action` on line 6. So it was just being run twice, which is unnecessary.

**Comment by JesseWeinstein** [comment]
Hm, regarding factoring it out into a method... It seems best to put it in the Point model -- that way it can be used both by Service and Case (each of which `has_many :points`). But I'm not entirely sure how to write that. Suggestions?

**Comment by JesseWeinstein** [comment]
Given how long this has gone for, can we just merge it and fix the concerns in a later PR?

**Comment by madoleary** [comment]
Okay, but the remaining concerns should be specified in issues, I think.

**Comment by JesseWeinstein** [comment]
OK, created #854 and #855 . Merging now.

**Pull request merged**
