### PR TITLE
 Fix conflicting function names 

### LINKED ISSUE #817: "Order Services By Rating" does not work
The "Order ServicesBy Rating" turns red when I press it, but doesn't actually sort; it does seem to change the order, but not in any understandable way.

### PR DESCRIPTION
**Pull request by Vinnl**
* [x] Are you working on the latest release?
* [x] Have you tested it locally?
* [x] Please explain your change

The functions for sorting services and points had the same name,
even though they behaved differently (i.e. sorting on A, B, C, etc.
vs. on Good, Bad, etc.), and therefore did not work.

I also changed IDs to class names, since they weren't unique.

Fixes #817.

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
Thanks for doing this; it does work now. But there's another related bug; when you click the button, the column headers vanish; and don't even come back when you click again.

**Comment by JesseWeinstein** [comment]
Well, it partially works -- when sorting on Services, only the top few are sorted; there's a bunch down at the bottom that aren't. :-(

**Comment by Vinnl** [comment]
@JesseWeinstein Thanks for giving it a try. Could you open a new Issue for that? I probably won't have time to look at it again any time soon, but perhaps someone else might :)

**Comment by JesseWeinstein** [comment]
Done -- see #822 .

**Pull request merged**
