### PR TITLE
documents model

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
I should have used `rails generate controller Documents` (plural). Fixed that now.
Now doing `rails generate model Document` (singular)

**Comment by piks3l** [comment]
in any case, you can run `rails destroy controller document` it will destroy the files it automatically created

**Comment by michielbdejong** [comment]
The `/documents/new` form now posts to itself instead of to `/documents`. Also, there is no link between documents and services yet.

**Comment by michielbdejong** [comment]
left to do:

* [ ] import current tosback2 docs
* [ ] script to export to tosback2 rules files
* [ ] check CRUD navigation (show,edit icons in index options, etc)
* [ ] rewrite services annotate view

**Comment by michielbdejong** [comment]
Before merging this PR:
* [ ] display already quoted points in annotate view
* [ ] display quote-less points in annotate view
* [ ] remove quote from points view
* [ ] update import script to also import text
* [ ] change point model to have document_id instead of quoteDoc/quoteRev
* [ ] make script re-index quoted points
* [ ] general sanity check

After merging:
* [ ] `rails db: migrate`
* [ ] import rules and text
* [ ] script to export to tosback2 rules files

**Comment by michielbdejong** [comment]
Leaving navigation for now, since annotation is still a bit of a hidden feature for now.

**Pull request merged**
