### PR TITLE
Added descriptions of cases as tooltips to the case overview.

### LINKED ISSUE #903: make case descriptions more prominent
they are useful but you only see them when you for instance visit https://edit.tosdr.org/cases/141

### PR DESCRIPTION
**Pull request by JustinBack**
This PR adds descriptions as tooltips to the case overview

Fixes #903

### CODE REVIEW

**Comment by JustinBack** [comment]
Added commits for #835 as well. Topic descriptions are now displayed as a tooltip while hovering over the topic.

**Comment by JustinBack** [comment]
The topic page now displays the subtitle, description and title using the subscript HTML tag

 This fixes #835

**Review by michielbdejong — APPROVED** [review]

**Comment by michielbdejong** [comment]
w00t!

**Comment by ToSDRForum** [comment]
This pull request has been mentioned on **ToS;DR Reviewers Forum**. There might be relevant details there:

https://forum.tosdr.org/t/case-topic-descriptions-needed/217/1

**Pull request merged**
