### PR TITLE
Fix: update of user details without the need of a password (460)

### PR DESCRIPTION
**Pull request by evilcel3ri**
Fixing #460 by using Devise default methods. However, the [recommended method](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-account-without-providing-a-password) for this doesn't work. I need to investigate, so far, just saving.

### CODE REVIEW

**Comment by michielbdejong** [comment]
I tried this but see the following:
> Password
> must include at least one lowercase letter, one uppercase letter, and one digit
> leave it blank if you don't want to change it

@piks3l can you test this again locally yourself?

**Comment by piks3l** [comment]
I have the more or less the same problem. I believe the problem comes from the validation of the `params` received by the controller (`current_password` cannot be blank or is unknown). Although the `update_without_password` method should override this, I'll look deeper in the doc to understand why it doens't work.

**Comment by piks3l** [comment]
So, it works now, the problem was coming from a custom validation I did on the User.rb model few months ago. I removed it and applied what Devise documentation recommends on this. 

Also, now users can change their details without putting a password, that means they can also choose a new weak password. I don't know if that's good as a trade-off.

Plus, I removed the `app/views/users/` folders as a refacto effort that I did. It was duplicate of `app/views/devise/`and wasn't doing anything. I fixed the routes accordingly.

**Review by michielbdejong — CHANGES_REQUESTED** [review]
When leaving the 'confirm password' input empty, neither an error is displayed, nor is the password changed.

But you get redirected to the main page, so the user would think that the password change was probably successful.

**Comment by piks3l** [comment]
> When leaving the 'confirm password' input empty, neither an error is displayed, nor is the password changed.

> But you get redirected to the main page, so the user would think that the password change was probably successful.

Ok, I'll work on this. Thanks !

**Comment by michielbdejong** [comment]
Merged in the master branch.

**Comment by piks3l** [comment]
Ok, the new solution, instead of messing too much with the form (because it was bit hard). I tricked the UX. Basically now you seem to have 2 forms. But in case you don't provided your current password, it won't change your password. I tried various solution but ended up intercepting the password of the user mid-process and I don't think that's what we want. 

@michielbdejong tell me what do you think. As the issue was mainly UX, I think this little trick does the job.

**Comment by Vinnl** [comment]
I haven't worked with the registration or with Device, so since I don't really feel equipped to perform a proper review, I'm unassigning myself for reviewing. That said, @piks3l, there appears to be a bunch of code in here unrelated to updating of a password, which both makes reviewing more difficult/time consuming, as well as increasing the likelihood of running into merge conflicts. You might want to split it up in different pull requests, or at least keep that in mind for the next time ;)

**Review by Vinnl — APPROVED** [review]
Oh, I can't unassign myself from reviewing, so I'm just blindly approving it now :P

**Comment by christalib** [comment]
Note for self: #564 + #560

**Pull request closed without merging**
