### PR TITLE
use same rating system as tosdr.org site

### PR DESCRIPTION
**Pull request by michielbdejong**
Not sure if we want to do this, but I thought it might be a good opportunity to fix https://github.com/tosdr/tosdr.org/issues/183

We may want to change how tosdr.org ratings work, but at least, we should not make such a change only in phoenix because then the two diverge.

### CODE REVIEW

**Comment by michielbdejong** [comment]
btw, since phoenix does not have a 'weight' for points (only the blocker:0, bad:2, neutral:5, good:8 rating), this basically sets all weights to 50, when compared to tosdr.org.

**Comment by piks3l** [comment]
I feel this weight can be complicated UX-wise. How are weights decided ? From the user's point of view ? Can a curator modify it ?

**Comment by michielbdejong** [comment]
I updated https://github.com/tosdr/phoenix/wiki to describe how (I think) rating currently works.

**Comment by michielbdejong** [comment]
I'll rebase this on top of #373

**Comment by michielbdejong** [comment]
@piks3l @madoleary @Vinnl this is a fundamental change, please all review if you agree with this change or have different plans for how this should work, to make sure we're on the same page.

**Review by evilcel3ri — APPROVED** [review]
Good for me!

**Review by Vinnl — APPROVED** [review]
It looks like a reasonable way to calculate the labels to me. :)

**Comment by michielbdejong** [comment]
@madoleary ?

**Review by madoleary — APPROVED** [review]

**Pull request merged**
